### ISSUE TITLE
Unable to get blinky to flash (or blink?) on ch32v003 petal

### ISSUE THREAD

**Issue by ghangaskan** [Hack-a-Day/2024-Supercon-8-Add-On-Badge#19]
After this part, I didn't get a blinky
>>> flasher.flash_binary("blink.bin")
Time spent: 120133
0x0 0x0
0x1 0x0
0x2 0x0
0x3 0x0

Log of stuff I tried:
```

Traceback (most recent call last):
  File "main.py", line 54, in <module>
KeyboardInterrupt: 
MicroPython v1.23.0 on 2024-06-02; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
MicroPython v1.23.0 on 2024-06-02; Raspberry Pi Pico W with RP2040

Type "help()" for more information.

>>> from flash_ch32v003 import CH32_Flash
>>> flasher = CH32_Flash(1)
>>> flasher.flash_binary("blink.bin")
Time spent: 120133
0x0 0x0
0x1 0x0
0x2 0x0
0x3 0x0
>>> flasher.enter_debug_mode
<bound_method>
>>> flasher.monitor()





Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "flash_ch32v003.py", line 257, in monitor
KeyboardInterrupt: 
>>> flasher.enter_debug_mode()
>>> flasher.monitor()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "flash_ch32v003.py", line 257, in monitor
KeyboardInterrupt: 
>>> 
```

**Comment by aaroneiche** [comment]
That looks to me like it's not flashing any data. I would expect it to look something like this: 
```
>>> flasher.flash_binary("blink_250.bin")
Time spent: 157374
0x0 0xa00006f
0x1 0x0
0x2 0x11c
0x3 0x11a
```
Try this `blink` binary. It should blink at 1/4" interval. 
[blink_250.bin.zip](https://github.com/user-attachments/files/17938102/blink_250.bin.zip)

**Comment by ghangaskan** [comment]
oh, yes, I get no signs of life at all. I get the same responses if I have no board plugged in. I'm sure I must have nuked my petal. Oh well (shrug)
